# Configuracion principal
title: Vicente Portafolio
description: ->
  Portafolio de vicentefelipechile

# Configuracion web
remote_theme: pages-themes/modernist@v0.2.0
# plugins:
# - jekyll-remote-theme
